title: Vik's think space
author: Viktor Bezhenar
email: viktor.bezhenar@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
  Viktor Bezhenar is an experienced project management professional that likes to write about
  software development processes, product development, tech trends, just trends and thoughts: so any stuff that comes to mind

theme: minima

twitter_username: vityawassup
github_username: viktorbezhenar
#linkedin_username: viktor-bezhenar-baaa7657
#facebook_username: viktor.bezhenar.5

header_pages:

 - Bookmarks.md
 - about.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag

show_excerpts: true
